apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-castflix-deployment
  labels:
    app: editor-castflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor-castflix
  template:
    metadata:
      labels:
        app: editor-castflix
    spec:
      containers:
      - name: editor-castflix
        image: omegup/editor-castflix:667e398
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: editor-castflix-service
spec:
  type: NodePort
  selector:
    app: editor-castflix
  ports:
    - port: 80
      targetPort: 80
