apiVersion: apps/v1
kind: Deployment
metadata:
 creationTimestamp: null
 labels:
   app: sync-invoice
 name: sync-invoice
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sync-invoice
 strategy: {}
 template:
   metadata:
     creationTimestamp: null
     labels:
       app: sync-invoice
   spec:
     containers:
       - args:
           - --expose-gc
           - invoice.js
         env:
           - name: MONGO_URL
             value: mongodb://mongo-school:27017/meteor?replicaSet=rs0&directConnection=true
         image: omegup/school-sync-invoice:V1.3.2
         name: sync-invoice
         resources: {}
     restartPolicy: Always
status: {}
