apiVersion: apps/v1
kind: Deployment
metadata:
 creationTimestamp: null
 labels:
   app: sync-attendance
 name: sync-attendance
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sync-attendance
 strategy: {}
 template:
   metadata:
     creationTimestamp: null
     labels:
       app: sync-attendance
   spec:
     containers:
       - args:
           - --expose-gc
           - attendance.js
         env:
           - name: MONGO_URL
             value: mongodb://mongo-school:27017/meteor?replicaSet=rs0&directConnection=true
         image: omegup/school-sync-attendance:V1.2.3
         name: sync-attendance
         resources: {}
     restartPolicy: Always
status: {}
