apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-school
  labels:
    app: back-school
spec:
  replicas: {{ .Values.backSchool.replicas }}
  selector:
    matchLabels:
      app: back-school
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: back-school
      annotations:
        commit-id: "{{ .Values.commitTrack }}"
    spec:
      containers:
        - name: back-school
          image: omegup/school-back:{{ include "school-app.commitTag" . }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backSchool.containerPort }}
          env:
          - name: METEOR_SETTINGS
            value: {{ .Values.backSchool.meteorSettings | toJson | quote }}
          - name: MONGO_OPLOG_URL
            value: {{ .Values.mongoOplogUrl | quote }}
          - name: MONGO_URL
            value: {{ .Values.mongoUrl | quote }}
          - name: PORT
            value: {{ .Values.backSchool.port | quote }}
          - name: ROOT_URL
            value: {{ .Values.backSchool.rootUrl | quote }}
          - name: SCHOOL_LOGO
            value: {{ .Values.backSchool.SCHOOL_LOGO | quote }}
          - name: SCHOOL_EMAIL
            value: {{ .Values.backSchool.SCHOOL_EMAIL | quote }}
          - name: SCHOOL_PHONE
            value: {{ .Values.backSchool.SCHOOL_PHONE | quote }}
          - name: SCHOOL_NAME
            value: {{ .Values.backSchool.SCHOOL_NAME | quote }}
          - name: SCHOOL_FACEBOOK
            value: {{ .Values.backSchool.SCHOOL_FACEBOOK | quote }}
          - name: SCHOOL_YOUTUBE
            value: {{ .Values.backSchool.SCHOOL_YOUTUBE | quote }}
          - name: SCHOOL_INSTAGRAM
            value: {{ .Values.backSchool.SCHOOL_INSTAGRAM | quote }}
          - name: SCHOOL_LINKEDIN
            value: {{ .Values.backSchool.SCHOOL_LINKEDIN | quote }}
          - name: SCHOOL_TWITTER
            value: {{ .Values.backSchool.SCHOOL_TWITTER | quote }}
          - name: SCHOOL_URL
            value: {{ .Values.backSchool.SCHOOL_URL | quote }}
          - name: SCHOOL_MAX_USERS
            value: {{ .Values.backSchool.SCHOOL_MAX_USERS | quote }}
          - name: LIMIT
            value: {{ .Values.backSchool.LIMIT | quote }}
          - name: LANG_SYSTEM
            value: {{ .Values.backSchool.LANG_SYSTEM | quote }}
          - name: SERVER_SYNC_IP     
            value: {{ .Values.SERVER_SYNC_IP | quote }}
          - name: SERVER_SYNC_PORT
            value: {{ .Values.SERVER_SYNC_PORT | quote }}
          volumeMounts:
            - mountPath: /data/back
              name: data-school-back
      restartPolicy: Always
      volumes:
        - name: data-school-back
          persistentVolumeClaim:
            claimName: {{ include "school-app.back-school.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: back-school
spec:
  ports:
    - name: "http"
      port: {{ .Values.backSchool.servicePort }}
      targetPort: {{ .Values.backSchool.serviceTargetPort }}
  selector:
    app: back-school
