apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-school
  labels:
    app: front-school
spec:
  replicas: {{ .Values.frontSchool.replicas }}
  selector:
    matchLabels:
      app: front-school
  template:
    metadata:
      labels:
        app: front-school
      annotations:
        commit-id: "{{ .Values.commitTrack }}"
    spec:
      containers:
      - name: front-school
        image: omegup/school-front:{{ include "school-app.commitTag" . }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontSchool.containerPort }}
        env:
        - name: BACKEND_SERVER
          value: {{ .Values.backendServer }}
        - name: LETSENCRYPT_EMAIL
          value: {{ .Values.letsencryptEmail }}
        - name: LETSENCRYPT_HOST
          value: {{ .Values.letsencryptHost }}
        - name: VIRTUAL_HOST
          value: {{ .Values.virtualHost }}
        - name: VIRTUAL_PORT
          value: "{{ .Values.virtualPort }}"
        - name: PUSH_SERVER_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: PUSH_SERVER_PUBLIC_KEY
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: API_KEY
        - name: AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: AUTH_DOMAIN
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: PROJECT_ID
        - name: STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: STORAGE_BUCKET
        - name: MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: MESSAGING_SENDER_ID
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: APP_ID
        - name: MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-secrets
              key: MEASUREMENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: front-school
  labels:
    app: front-school
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.frontSchool.containerPort }}
    targetPort: {{ .Values.frontSchool.containerPort }}
  selector:
    app: front-school
