apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 0 * * *" # At midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            role: {{ .Values.workerBackup | quote }}
          containers:
          - name: mongodb-backup
            image: bitnami/mongodb:6.0.0 # Replace with the appropriate MongoDB image
            env:
            - name: MONGO_URL
              value: {{ .Values.mongoUrl | quote }}
            - name: APP_NAME
              value: {{ include "school-app.name" . }}
            command:
            - /bin/bash
            - -c
            - |
              mongodump \
                --uri=$(MONGO_URL)\
                --archive=/backups/${APP_NAME}/backup-$(date +\%Y-\%m-\%d_\%H-\%M-\%S).gz
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: {{ include "school-app.mongodb-backup.fullname" . }}
