apiVersion: v1
kind: Service
metadata:
  name: {{ include "school-app.mongo.fullname" . }}
  labels:
    app: {{ include "school-app.mongo.name" . }}
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    app: {{ include "school-app.mongo.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: 27017
