apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-dispatcher
spec:
  replicas: {{ .Values.notifDispatcher.replicas }}
  selector:
    matchLabels:
      app: notif-dispatcher
  template:
    metadata:
      labels:
        app: notif-dispatcher
      annotations:
        commit-id: "{{ .Values.commitTrack }}"
    spec:
      containers:
      - name: notif-dispatcher
        image: omegup/notif-dispatcher:{{ .Values.env.commitTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.notifDispatcher.containerPort }}
        env:
        - name: MONGO_URL
          value: "{{ .Values.mongoUrl }}"
        - name: RABBITMQ_URL
          value: "{{ .Values.rabbitmqUrl }}"
---
apiVersion: v1
kind: Service
metadata:
  name: notif-dispatcher
spec:
  selector:
    app: notif-dispatcher
  ports:
  - protocol: TCP
    port: {{ .Values.notifDispatcher.containerPort }}
    targetPort: {{ .Values.notifDispatcher.containerPort }}
