apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-notifications
  labels:
    app: sync-notifications
spec:
  replicas: {{ .Values.sync.replicas }}
  selector:
    matchLabels:
      app: sync-notifications
  template:
    metadata:
      labels:
        app: sync-notifications
      annotations:
        commit-id: "{{ .Values.commitTrack }}"
    spec:
      containers:
      - args:
        - --expose-gc
        - notifications.js
        env:
        - name: MONGO_URL
          value: "{{ .Values.mongoUrl }}"
        image: omegup/school-sync:{{ include "school-app.commitTag" . }}
        imagePullPolicy: Always
        name: sync-notifications
      restartPolicy: Always
