apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-server
  labels:
    app: sync-server
spec:
  replicas: {{ .Values.sync.replicas }}
  selector:
    matchLabels:
      app: sync-server
  template:
    metadata:
      labels:
        app: sync-server
      annotations:
        commit-id: "{{ .Values.commitTrack }}"
    spec:
      containers:
      - args:
        - --expose-gc
        - server.js
        env:
        - name: MONGO_URL
          value: "{{ .Values.mongoUrl }}"
        - name: SERVER_SYNC_IP     
          value: {{ .Values.SERVER_SYNC_IP | quote }}
        - name: SERVER_SYNC_PORT
          value: {{ .Values.SERVER_SYNC_PORT | quote }}
        image: omegup/school-sync:{{ include "school-app.commitTag" . }}
        imagePullPolicy: Always
        name: sync-server
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sync-server
spec:
  type: ClusterIP
  selector:
    app:  sync-server
  ports:
  - port: 4500
    targetPort: 4500
    protocol: TCP