apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-classes
  labels:
    app: sync-classes
spec:
  replicas: {{ .Values.sync.replicas }}
  selector:
    matchLabels:
      app: sync-classes
  template:
    metadata:
      labels:
        app: sync-classes
      annotations:
        commit-id: "{{ .Values.commitTrack }}"
    spec:
      containers:
      - args:
        - --expose-gc
        - classes.js
        env:
        - name: MONGO_URL
          value: "{{ .Values.mongoUrl }}"
        image: omegup/school-sync-classes:{{ .Values.commitTag }}
        imagePullPolicy: Always
        name: sync-classes
      restartPolicy: Always
