apiVersion: v1
kind: Service
metadata:
 creationTimestamp: null
 name: back-school
spec:
 ports:
   - name: "3001"
     port: 3001
     targetPort: 3001
 selector:
   app: back-school
status:
 loadBalancer: {}
