apiVersion: v1
kind: Service
metadata:
  name: mongo-school
  labels:
    app: mongo-school
spec:
  selector:
    app: mongo-school
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
